"""Added all tables

Revision ID: 581dddd6bf4a
Revises: 
Create Date: 2020-12-09 12:34:03.739023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581dddd6bf4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Countries',
    sa.Column('code', sa.VARCHAR(length=5), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('Customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('TIN', sa.VARCHAR(length=10), nullable=False),
    sa.Column('CIO', sa.VARCHAR(length=9), nullable=False),
    sa.Column('MGRN', sa.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Partners_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_of_contract_begin', sa.DATE(), nullable=False),
    sa.Column('date_of_contract_end', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tour_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tour_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('passport_data', sa.VARCHAR(length=12), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=12), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date_of_registration', sa.DATE(), nullable=False),
    sa.Column('insurance_number', sa.VARCHAR(length=13), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('foreign_passport_data', sa.VARCHAR(length=12), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['Customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Hotels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('count_of_stars', sa.Integer(), nullable=False),
    sa.Column('count_of_place', sa.Integer(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=False),
    sa.Column('parking', sa.Boolean(), nullable=False),
    sa.Column('transfer', sa.Boolean(), nullable=False),
    sa.Column('country_code', sa.VARCHAR(length=5), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['Countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['Partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Services_inside_tours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('tour_service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['Tours.id'], ),
    sa.ForeignKeyConstraint(['tour_service_id'], ['Tour_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Types_inside_tours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tour_type_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['Tours.id'], ),
    sa.ForeignKeyConstraint(['tour_type_id'], ['Tour_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Hotels_inside_tours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['Hotels.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['Tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Hotels_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['Hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['Hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Services_inside_hotels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['Hotels.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['Services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tour_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_request', sa.DATE(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('date_of_begin', sa.DATE(), nullable=False),
    sa.Column('count_of_nights', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('tours_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['Partners.id'], ),
    sa.ForeignKeyConstraint(['tours_id'], ['Tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Clients_contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_contract', sa.DATE(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('tour_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['Clients.id'], ),
    sa.ForeignKeyConstraint(['tour_request_id'], ['Tour_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Vouchers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voucher', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tour_request_id', sa.Integer(), nullable=False),
    sa.Column('client_contract_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_contract_id'], ['Clients_contracts.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['Services.id'], ),
    sa.ForeignKeyConstraint(['tour_request_id'], ['Tour_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vouchers')
    op.drop_table('Clients_contracts')
    op.drop_table('Tour_requests')
    op.drop_table('Services_inside_hotels')
    op.drop_table('Reviews')
    op.drop_table('Hotels_photo')
    op.drop_table('Hotels_inside_tours')
    op.drop_table('Types_inside_tours')
    op.drop_table('Services_inside_tours')
    op.drop_table('Services')
    op.drop_table('Hotels')
    op.drop_table('Clients')
    op.drop_table('Tours')
    op.drop_table('Tour_types')
    op.drop_table('Tour_services')
    op.drop_table('Partners_contracts')
    op.drop_table('Partners')
    op.drop_table('Customers')
    op.drop_table('Countries')
    # ### end Alembic commands ###
