"""Change value in Countries

Revision ID: f1ddfccf52c5
Revises: 504dce1bc5a4
Create Date: 2020-12-09 13:10:43.255362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ddfccf52c5'
down_revision = '504dce1bc5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
